root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  api/: api-documentation.md
  deposit-flow/: deposit-flow.md
  architecture/: technical-architecture.md
  manager-notifications/: manager-notifications.md